version: 2

models:
  - name: stg_production_database__brands
    description: "This model contains information about brands of the bikes sold"
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brands"
        tests:
            - unique
            - not_null


  - name: stg_production_database__categories
    description: "This model contains information about categories of bikes sold."
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each categories."
        tests:
            - unique
            - not_null

  - name: stg_production_database__products
    description: "This model contains information about each products brand, category, model_year, unit_price"
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product item."
        tests:
            - unique
            - not_null
      - name: brand_id
        description: "Foreign key linking the product item to the corresponding brand."
        tests:
          - relationships:
              name: brand_id_id_foreign_key_in_stg_production_database__brands
              to: ref('stg_production_database__brands')
              field: brand_id
      - name: category_id
        description: "Foreign key linking the product item to the corresponding category."
        tests:
          - relationships:
              name: category_id_id_foreign_key_in_stg_production_database__categories
              to: ref('stg_production_database__categories')
              field: category_id

  - name: stg_production_database__stocks
    description: "This model contains information about the stocks_quantity of each products in each stores"
    columns:
      - name: stock_id
        description: "Primary key, unique identifier for each stocks: generated by concatenating store_id and product_id."
        tests:
            - unique
            - not_null
      - name: product_id
        description: "Foreign key linking the product item to the corresponding quantity."
        tests:
          - relationships:
              name: brand_id_id_foreign_key_in_stg_production_database__products
              to: ref('stg_production_database__brands')
              field: product_id
      - name: store_id
        description: "Foreign key linking the product item to the corresponding store."
        tests:
          - relationships:
              name: store_id_id_foreign_key_in_stg_sale_database__stores
              to: ref('stg_sale_database__stores')
              field: store_id