version: 2

sources:
  - name: production_database
    schema: production_database
    tables:
      - name: brands
      - name: categories
      - name: products
      - name: stocks


  - name: sale_database
    schema: sale_database
    tables:
      - name: customers
      - name: order_items
      - name: orders
      - name: staffs
      - name: stores